// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 16.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EFCore.TextTemplating
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Scaffolding;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal partial class DbContextGenerator : EFCore.TextTemplating.CodeGeneratorBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextNamespace));
            this.Write("\r\n{\r\n    using ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ConfigurationContextFolder));
            this.Write(";\r\n    using Microsoft.EntityFrameworkCore;\r\n\r\n    /// <summary>\r\n    /// ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextName));
            this.Write("\r\n    /// </summary>\r\n    /// <inheritdoc />\r\n    public partial class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextName));
            this.Write(" : DbContext\r\n    {\r\n        /// <inheritdoc />\r\n        protected ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextName));
            this.Write("()\r\n        {\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextName));
            this.Write("(DbContextOptions<");
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextName));
            this.Write("> options)\r\n            : base(options)\r\n        {\r\n        }\r\n\r\n");

    foreach (var entityType in Model.GetEntityTypes())
    {
        var tableName = entityType.GetTableName();
        var isView = entityType.FindAnnotation("Relational:ViewDefinition") != null;

            this.Write("        /// <summary>\r\n        /// ");
            this.Write(this.ToStringHelper.ToStringWithCulture(entityType.Name));
            this.Write(this.ToStringHelper.ToStringWithCulture(isView ? string.Empty : ("(" + tableName+ ")")));
            this.Write("\r\n        /// </summary>\r\n        public virtual DbSet<");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetEntityClassName(entityType)));
            this.Write("> ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetEntityName(entityType)));
            this.Write(" { get; set; }\r\n\r\n");

    }


            this.Write(@"        /// <inheritdoc />
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#if DEBUG
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder");
            this.Write(this.ToStringHelper.ToStringWithCulture(Code.Fragment(ProviderCode.GenerateUseProvider(ConnectionString))));
            this.Write(";\r\n#endif\r\n            }\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        protec" +
                    "ted override void OnModelCreating(ModelBuilder modelBuilder)\r\n        {\r\n");

    foreach (var entityType in Model.GetEntityTypes())
    {

            this.Write("            modelBuilder.ApplyConfiguration(new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetEntityConfigurationName(entityType)));
            this.Write("());\r\n");

    }

            this.Write("\r\n            OnModelCreatingPartial(modelBuilder);\r\n        }\r\n\r\n        partial" +
                    " void OnModelCreatingPartial(ModelBuilder modelBuilder);\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }

private global::Microsoft.EntityFrameworkCore.Metadata.IModel _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::Microsoft.EntityFrameworkCore.Metadata.IModel Model
{
    get
    {
        return this._ModelField;
    }
}

private string _ContextNamespaceField;

/// <summary>
/// Access the ContextNamespace parameter of the template.
/// </summary>
private string ContextNamespace
{
    get
    {
        return this._ContextNamespaceField;
    }
}

private string _ModelNamespaceField;

/// <summary>
/// Access the ModelNamespace parameter of the template.
/// </summary>
private string ModelNamespace
{
    get
    {
        return this._ModelNamespaceField;
    }
}

private string _ContextNameField;

/// <summary>
/// Access the ContextName parameter of the template.
/// </summary>
private string ContextName
{
    get
    {
        return this._ContextNameField;
    }
}

private string _ConnectionStringField;

/// <summary>
/// Access the ConnectionString parameter of the template.
/// </summary>
private string ConnectionString
{
    get
    {
        return this._ConnectionStringField;
    }
}

private bool _SuppressConnectionStringWarningField;

/// <summary>
/// Access the SuppressConnectionStringWarning parameter of the template.
/// </summary>
private bool SuppressConnectionStringWarning
{
    get
    {
        return this._SuppressConnectionStringWarningField;
    }
}

private bool _UseDataAnnotationsField;

/// <summary>
/// Access the UseDataAnnotations parameter of the template.
/// </summary>
private bool UseDataAnnotations
{
    get
    {
        return this._UseDataAnnotationsField;
    }
}

private global::Microsoft.EntityFrameworkCore.Design.ICSharpHelper _CodeField;

/// <summary>
/// Access the Code parameter of the template.
/// </summary>
private global::Microsoft.EntityFrameworkCore.Design.ICSharpHelper Code
{
    get
    {
        return this._CodeField;
    }
}

private global::Microsoft.EntityFrameworkCore.Scaffolding.IProviderConfigurationCodeGenerator _ProviderCodeField;

/// <summary>
/// Access the ProviderCode parameter of the template.
/// </summary>
private global::Microsoft.EntityFrameworkCore.Scaffolding.IProviderConfigurationCodeGenerator ProviderCode
{
    get
    {
        return this._ProviderCodeField;
    }
}

private global::Microsoft.EntityFrameworkCore.Design.IAnnotationCodeGenerator _AnnotationCodeField;

/// <summary>
/// Access the AnnotationCode parameter of the template.
/// </summary>
private global::Microsoft.EntityFrameworkCore.Design.IAnnotationCodeGenerator AnnotationCode
{
    get
    {
        return this._AnnotationCodeField;
    }
}

private string _ConfigurationContextFolderField;

/// <summary>
/// Access the ConfigurationContextFolder parameter of the template.
/// </summary>
private string ConfigurationContextFolder
{
    get
    {
        return this._ConfigurationContextFolderField;
    }
}

private global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String> _GetEntityNameField;

/// <summary>
/// Access the GetEntityName parameter of the template.
/// </summary>
private global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String> GetEntityName
{
    get
    {
        return this._GetEntityNameField;
    }
}

private global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String> _GetEntityClassNameField;

/// <summary>
/// Access the GetEntityClassName parameter of the template.
/// </summary>
private global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String> GetEntityClassName
{
    get
    {
        return this._GetEntityClassNameField;
    }
}

private global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String> _GetEntityConfigurationNameField;

/// <summary>
/// Access the GetEntityConfigurationName parameter of the template.
/// </summary>
private global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String> GetEntityConfigurationName
{
    get
    {
        return this._GetEntityConfigurationNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::Microsoft.EntityFrameworkCore.Metadata.IModel)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::Microsoft.EntityFrameworkCore.Metadata.IModel)(data));
    }
}
bool ContextNamespaceValueAcquired = false;
if (this.Session.ContainsKey("ContextNamespace"))
{
    this._ContextNamespaceField = ((string)(this.Session["ContextNamespace"]));
    ContextNamespaceValueAcquired = true;
}
if ((ContextNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ContextNamespace");
    if ((data != null))
    {
        this._ContextNamespaceField = ((string)(data));
    }
}
bool ModelNamespaceValueAcquired = false;
if (this.Session.ContainsKey("ModelNamespace"))
{
    this._ModelNamespaceField = ((string)(this.Session["ModelNamespace"]));
    ModelNamespaceValueAcquired = true;
}
if ((ModelNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ModelNamespace");
    if ((data != null))
    {
        this._ModelNamespaceField = ((string)(data));
    }
}
bool ContextNameValueAcquired = false;
if (this.Session.ContainsKey("ContextName"))
{
    this._ContextNameField = ((string)(this.Session["ContextName"]));
    ContextNameValueAcquired = true;
}
if ((ContextNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ContextName");
    if ((data != null))
    {
        this._ContextNameField = ((string)(data));
    }
}
bool ConnectionStringValueAcquired = false;
if (this.Session.ContainsKey("ConnectionString"))
{
    this._ConnectionStringField = ((string)(this.Session["ConnectionString"]));
    ConnectionStringValueAcquired = true;
}
if ((ConnectionStringValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ConnectionString");
    if ((data != null))
    {
        this._ConnectionStringField = ((string)(data));
    }
}
bool SuppressConnectionStringWarningValueAcquired = false;
if (this.Session.ContainsKey("SuppressConnectionStringWarning"))
{
    this._SuppressConnectionStringWarningField = ((bool)(this.Session["SuppressConnectionStringWarning"]));
    SuppressConnectionStringWarningValueAcquired = true;
}
if ((SuppressConnectionStringWarningValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("SuppressConnectionStringWarning");
    if ((data != null))
    {
        this._SuppressConnectionStringWarningField = ((bool)(data));
    }
}
bool UseDataAnnotationsValueAcquired = false;
if (this.Session.ContainsKey("UseDataAnnotations"))
{
    this._UseDataAnnotationsField = ((bool)(this.Session["UseDataAnnotations"]));
    UseDataAnnotationsValueAcquired = true;
}
if ((UseDataAnnotationsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("UseDataAnnotations");
    if ((data != null))
    {
        this._UseDataAnnotationsField = ((bool)(data));
    }
}
bool CodeValueAcquired = false;
if (this.Session.ContainsKey("Code"))
{
    this._CodeField = ((global::Microsoft.EntityFrameworkCore.Design.ICSharpHelper)(this.Session["Code"]));
    CodeValueAcquired = true;
}
if ((CodeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Code");
    if ((data != null))
    {
        this._CodeField = ((global::Microsoft.EntityFrameworkCore.Design.ICSharpHelper)(data));
    }
}
bool ProviderCodeValueAcquired = false;
if (this.Session.ContainsKey("ProviderCode"))
{
    this._ProviderCodeField = ((global::Microsoft.EntityFrameworkCore.Scaffolding.IProviderConfigurationCodeGenerator)(this.Session["ProviderCode"]));
    ProviderCodeValueAcquired = true;
}
if ((ProviderCodeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ProviderCode");
    if ((data != null))
    {
        this._ProviderCodeField = ((global::Microsoft.EntityFrameworkCore.Scaffolding.IProviderConfigurationCodeGenerator)(data));
    }
}
bool AnnotationCodeValueAcquired = false;
if (this.Session.ContainsKey("AnnotationCode"))
{
    this._AnnotationCodeField = ((global::Microsoft.EntityFrameworkCore.Design.IAnnotationCodeGenerator)(this.Session["AnnotationCode"]));
    AnnotationCodeValueAcquired = true;
}
if ((AnnotationCodeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AnnotationCode");
    if ((data != null))
    {
        this._AnnotationCodeField = ((global::Microsoft.EntityFrameworkCore.Design.IAnnotationCodeGenerator)(data));
    }
}
bool ConfigurationContextFolderValueAcquired = false;
if (this.Session.ContainsKey("ConfigurationContextFolder"))
{
    this._ConfigurationContextFolderField = ((string)(this.Session["ConfigurationContextFolder"]));
    ConfigurationContextFolderValueAcquired = true;
}
if ((ConfigurationContextFolderValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ConfigurationContextFolder");
    if ((data != null))
    {
        this._ConfigurationContextFolderField = ((string)(data));
    }
}
bool GetEntityNameValueAcquired = false;
if (this.Session.ContainsKey("GetEntityName"))
{
    this._GetEntityNameField = ((global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String>)(this.Session["GetEntityName"]));
    GetEntityNameValueAcquired = true;
}
if ((GetEntityNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GetEntityName");
    if ((data != null))
    {
        this._GetEntityNameField = ((global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String>)(data));
    }
}
bool GetEntityClassNameValueAcquired = false;
if (this.Session.ContainsKey("GetEntityClassName"))
{
    this._GetEntityClassNameField = ((global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String>)(this.Session["GetEntityClassName"]));
    GetEntityClassNameValueAcquired = true;
}
if ((GetEntityClassNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GetEntityClassName");
    if ((data != null))
    {
        this._GetEntityClassNameField = ((global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String>)(data));
    }
}
bool GetEntityConfigurationNameValueAcquired = false;
if (this.Session.ContainsKey("GetEntityConfigurationName"))
{
    this._GetEntityConfigurationNameField = ((global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String>)(this.Session["GetEntityConfigurationName"]));
    GetEntityConfigurationNameValueAcquired = true;
}
if ((GetEntityConfigurationNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GetEntityConfigurationName");
    if ((data != null))
    {
        this._GetEntityConfigurationNameField = ((global::System.Func<Microsoft.EntityFrameworkCore.Metadata.IEntityType, System.String>)(data));
    }
}


    }
}


    }
}
