// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sample.Design
{
    using Microsoft.EntityFrameworkCore.Design;
    using Microsoft.EntityFrameworkCore.Metadata;
    using Microsoft.EntityFrameworkCore.Metadata.Internal;
    using Microsoft.EntityFrameworkCore.Scaffolding;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\brice\source\repos\Sample\Sample\Design\MyDbContextGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal partial class MyDbContextGenerator : MyCodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing Microsoft.EntityFrameworkCore;\r\nusing Microsoft.EntityFramew" +
                    "orkCore.Metadata;\r\n\r\nnamespace ");
            
            #line 10 "C:\Users\brice\source\repos\Sample\Sample\Design\MyDbContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic partial class ");
            
            #line 12 "C:\Users\brice\source\repos\Sample\Sample\Design\MyDbContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextName));
            
            #line default
            #line hidden
            this.Write(" : DbContext\r\n\t{\r\n");
            
            #line 14 "C:\Users\brice\source\repos\Sample\Sample\Design\MyDbContextGenerator.tt"

	foreach (var entityType in Model.GetEntityTypes())
	{

            
            #line default
            #line hidden
            this.Write("\t\tpublic virtual DbSet<");
            
            #line 18 "C:\Users\brice\source\repos\Sample\Sample\Design\MyDbContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityType.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 18 "C:\Users\brice\source\repos\Sample\Sample\Design\MyDbContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityType.Scaffolding().DbSetName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 19 "C:\Users\brice\source\repos\Sample\Sample\Design\MyDbContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t\tprotected override void OnConfiguring(DbContextOptionsBuilder options)\r\n\t\t    =" +
                    "> options");
            
            #line 23 "C:\Users\brice\source\repos\Sample\Sample\Design\MyDbContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Code.Fragment(ProviderCode.GenerateUseProvider(ConnectionString))));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t\tprotected override void OnModelCreating(ModelBuilder modelBuilder)\r\n\t\t{\r\n");
            
            #line 27 "C:\Users\brice\source\repos\Sample\Sample\Design\MyDbContextGenerator.tt"

	// TODO

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 33 "C:\Users\brice\source\repos\Sample\Sample\Design\MyDbContextGenerator.tt"

	public IModel Model { get; set; }
	public string Namespace { get; set; }
	public string ContextName { get; set; }
	public string ConnectionString { get; set; }

	public ICSharpHelper Code { get; set; }
	public IProviderConfigurationCodeGenerator ProviderCode { get; set; }
	public IAnnotationCodeGenerator Annotation { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
