// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sample.Design
{
    using Microsoft.EntityFrameworkCore.Design;
    using Microsoft.EntityFrameworkCore.Metadata;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\brice\source\repos\Sample\Sample\Design\MyEntityTypeGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal partial class MyEntityTypeGenerator : MyCodeGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.ComponentModel.Dat" +
                    "aAnnotations;\r\n\r\nnamespace ");
            
            #line 8 "C:\Users\brice\source\repos\Sample\Sample\Design\MyEntityTypeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class ");
            
            #line 10 "C:\Users\brice\source\repos\Sample\Sample\Design\MyEntityTypeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityType.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 12 "C:\Users\brice\source\repos\Sample\Sample\Design\MyEntityTypeGenerator.tt"

    foreach (var property in EntityType.GetProperties())
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 16 "C:\Users\brice\source\repos\Sample\Sample\Design\MyEntityTypeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Code.Reference(property.ClrType)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 16 "C:\Users\brice\source\repos\Sample\Sample\Design\MyEntityTypeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 17 "C:\Users\brice\source\repos\Sample\Sample\Design\MyEntityTypeGenerator.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 22 "C:\Users\brice\source\repos\Sample\Sample\Design\MyEntityTypeGenerator.tt"

    public IEntityType EntityType { get; set; }
    public string Namespace { get; set; }

    public ICSharpHelper Code { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
